platform :ios, '6.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'Reachability', '~> 3.1.1'
pod 'ReactiveCocoa', '~> 1.5.0'
pod 'ODRefreshControl', '~> 1.1.0'
pod 'BlocksKit', '~> 1.8.3'
pod 'ALAlertBanner', '~> 0.3.1'
pod 'ZBarSDK', '~> 1.3.1'
pod 'SDWebImage'
